Repository k3rnelpan1c-dev/uptime-kuma-helm, pull requests merged in 2023-09, with the labels that each got.

#137 fix: apprise install after bookworm update
  container/Containerfile
Labels: bug

#139 feat: support for trusting private CA
  uptime-kuma/Chart.yaml
  uptime-kuma/readme.adoc
  uptime-kuma/templates/configmap.yaml
  uptime-kuma/templates/statefulSet.yaml
  uptime-kuma/values.schema.json
  uptime-kuma/values.yaml
Labels: enhancement

#142 feat: utilise helm chart-releaser
  .github/renovate.json
  .github/workflows/helm-release.yaml
  charts/uptime-kuma/.helmignore
  charts/uptime-kuma/Chart.yaml
  charts/uptime-kuma/readme.adoc
  charts/uptime-kuma/templates/NOTES.txt
  charts/uptime-kuma/templates/_helpers.tpl
  charts/uptime-kuma/templates/configmap.yaml
  charts/uptime-kuma/templates/ingress.yaml
  charts/uptime-kuma/templates/pvc.yaml
  charts/uptime-kuma/templates/route.yaml
  charts/uptime-kuma/templates/secret.yaml
  charts/uptime-kuma/templates/service.yaml
  charts/uptime-kuma/templates/serviceaccount.yaml
  charts/uptime-kuma/templates/servicemonitor.yaml
  charts/uptime-kuma/templates/statefulSet.yaml
  charts/uptime-kuma/templates/tests/test-connection.yaml
  charts/uptime-kuma/values.schema.json
  charts/uptime-kuma/values.yaml
Labels: enhancement, ci, github-actions

#144 fix: chart-releaser action does not support tag trigger
  .github/workflows/helm-release.yaml
Labels: bug, ci

#145 fix: checkout depth to please chart-release action
  .github/workflows/helm-release.yaml
Labels: bug, ci
